### ISSUE TITLE
[Discussion] Disconnect method

### ISSUE THREAD

**Issue by asgeira13** [xdenser/node-firebird-libfbclient#121]
Just wanted to ask some stuff about closing connections with this library, sorry for opening it as an issue.

[link to method disconnect](https://github.com/xdenser/node-firebird-libfbclient/blob/55c97f250cc89c29f74ac82265bca4e0b030f06d/src/fb-bindings-connection.h#L79)

I noticed that in the fb-bindings-connection source files you already have a method for closing the client connection that seemed to work fine, when I made some generic testing. The documentation for this library does not mention this method at all and since I am using typescript, the @types file did also not make it available as a method of the "connection" object (of course that is  totally seperate from this project, I just found it interesting that the author of that library did not implement it).

I wanted to know if the author or anyone else had any comment on, if the method is still a work in progress or if it should be ok to use in the newest versions?  

If it is safe to use maybe we should add this as a small line in the README documentation? I personally managed to not see it for years until after checking the source folder.

**Comment by xdenser** [comment]
Yes it is supported method. It is tested, so it was just missing line in documentation.
