### ISSUE TITLE
dyld: missing symbol called on latest M1 Mac

### ISSUE THREAD

**Issue by TautFlorian** [xdenser/node-firebird-libfbclient#123]
`npm install` of latest version worked fine on the latest M1 Pro Mac with Firebird 3.0.8 for Mac installed.

When running a select statement inside the code im getting the following error all the time:
```
dyld[1870]: missing symbol called
sh: line 1: 1869 Abort trap: 6
```
The exact same project works fine on an Intel Mac with the same setup.
If you need me to test anything let me know.

Also happens when i try simple-ws sample script with connection to my database.

**Comment by xdenser** [comment]
No idea. I do not have Mac to try. Probably it requires some additional flags in binding.gyp.
Does Firebird client lib works for you on M1 from some other program?

**Comment by TautFlorian** [comment]
I can test `isql` tool if it relies on it. I'm not sure if there is a different tool to use.
DBeaver does not use it i think, i think it uses some Java library for the connection.

I will let you know once i tried.

**Comment by TautFlorian** [comment]
@xdenser I was finally able to try `isql` on the device. It works without any problems.
Do you know any other program that relies on firebird client lib? 

I did not find another npm package that uses it.

**Comment by tautf** [comment]
Is there any update on this or can somebody help? We still run into the same problem.

**Comment by tautf** [comment]
This is resolving it.
https://gist.github.com/adrienjoly/e29a6e73fb7e701eefd80ff9bde9abeb
