### ISSUE TITLE
Connection breaks after certain amount of time and no reconnect is possible

### ISSUE THREAD

**Issue by tautf** [xdenser/node-firebird-libfbclient#126]
Having another issue with the library.

After a certain amount of time, connection via our node app to the database is not possible anymore.
It works for multiple hours and then just breaks at a certain point.

Connecting to the database with the user defined for the library works fine via different tools, so its probably not a problem of the database itself.

Im pretty curious about the error message where he is trying to connect.
`Unable to complete network request to host "xnet://Global\FIREBIRD"`

As said, it works for several hours. Killing the application does not resolve the problem. A complete server reboot is needed.

Anybody ever seen this error message?

**Comment by xdenser** [comment]
Which OS, which version of Firebird?
If this is windows - maybe we should update lib files.
If this is linux - which version of lib fb client do you use?

**Comment by tautf** [comment]
I am currently trying something out that may be the solution, not sure yet.
We are using pm2 for service control.

We have the issue that pm2 is trying to restart our server multiple times in the background. The first thing our app does, is connecting to the database. So we assume that pm2 is restarting the server to often and to many db connections are made. We will see what happens here.

To your question. Its Windows Server 2019. Firebird 3.0.4, latest Version of your plugin.

Will come back with an update.

**Comment by tautf** [comment]
So we are pretty sure that pm2 is causing the trouble. After five days of runtime we did not have a breakdown.
