### ISSUE TITLE
should we commit?

### ISSUE THREAD

**Issue by sqllyw** [xdenser/node-firebird-libfbclient#127]
Hi,
sample code below, it's only reading, should we commitSync after the 'select'?
````
var fb  = require("./firebird");
sys = require("sys"); 
var con = fb.createConnection();
con.connectSync('test.fdb','sysdba','masterkey','');
var res = con.querySync("select * from test");
con.commitSync(); // needed?
var rows = res.fetchSync("all",true);
````

**Comment by jackdouglas** [comment]
> should we commitSync after the 'select'?

No, `con.commitSync()` just commits the transaction in Firebird, but you haven't done anything that need committing so it will have no effect.
