### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by gparbh** [xdenser/node-firebird-libfbclient#138]
npm install gives the following error
node version : 16.20.2

$ npm instal firebird
npm ERR! code 1
npm ERR! path C:\Users\user\Documents\Work\C32ToJson-NodeJS\node_modules\firebird
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.20.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.0 found at "C:\Python\Python312\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.20.2/node-v16.20.2-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.20.2/node-v16.20.2-headers.tar.gz failed, reason: self signed certificate in certificate chain
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v16.20.2\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:494:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:525:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\nvm\\v16.20.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\user\Documents\Work\C32ToJson-NodeJS\node_modules\firebird
npm ERR! gyp ERR! node -v v16.20.2
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2024-03-28T05_32_01_768Z-debug-0.log

**Comment by xdenser** [comment]
This has nothing to do with node-firebird-libfbclient. You are probably behind corporate firewall.
There are many advices on the internet how to solve this problem with node-gyp.
