### ISSUE TITLE
Node 4.0 compatibility

### ISSUE THREAD

**Issue by jacobalberty** [xdenser/node-firebird-libfbclient#58]
It seems this project is not currently working with node 4.0, I can provide the npm-debug.log if needed but after doing some digging i found it appears the main problem is it needs to be updated to NAN 2.x

**Comment by jacobalberty** [comment]
You can find my work to get it to compile at 
https://github.com/jacobalberty/node-firebird-libfbclient
I dont know if it works yet but it does compile...

**Comment by jacobalberty** [comment]
I did some reformatting of the coding style to make it easier to read as I figured out what was going on so the diff is needlessly big between the two
but it does compile, and connect and I've tested it with events.

The only change i've got a bad feeling about is in fb-bindings-result.cc around line 711
A direct translation would be 
Local<Value> ret = Nan::New(f_req->rowCallback->Call(1, argv));
But it doesn't compile so I tried removing the Nan::New() call around the callback call so it looks like
Local<Value> ret = f_req->rowCallback->Call(1, argv);
Documentation around the web indicated Local<Value>'s dont need to be instantiated that way. But i'm not sure if Nan::Callback() on its own will bring the value into the right context. I haven't run the unit tests yet, When I get a chance to get the unit test working I'll report back and do a pull request. If someone else happens to beat me to it, post here and let me know how the unit tests went.

**Comment by xdenser** [comment]
For me under Windows all tests pass.
I'll try linux tomorrow.

**Comment by jacobalberty** [comment]
Went ahead and opened the pull request so if you'd like to merge it in it's easier.

**Comment by jacobalberty** [comment]
One issue with the patch, It doesn't work on 0.12, fails to compile.
```
diff --git a/src/fb-bindings-fbeventemitter.cc b/src/fb-bindings-fbeventemitter.cc
index fa2178d..4ec6452 100644
--- a/src/fb-bindings-fbeventemitter.cc
+++ b/src/fb-bindings-fbeventemitter.cc
@@ -23,7 +23,7 @@ void FBEventEmitter::Initialize(v8::Handle<v8::Object> target)
 void FBEventEmitter::Emit(Handle<String> event, int argc, Handle<Value> argv[])
   {
        Nan::HandleScope scope;
-    Handle<Value> argv1[11];
+    Local<Value> argv1[11];
     if(argc>10) Nan::ThrowError("Cant process more than 10 arguments");
     argv1[0] = event;
     for(int i=0;i<argc;i++) argv1[i+1] = argv[i];
```
Seems to be a proper fix, it appears to be working for me in both 4.0 and 0.12.

**Comment by jacobalberty** [comment]
A step closer, Tests pass up to events for me now, using copybuffer instead of newbuffer. Events always fail for me no matter how i test them so this might be the one.
I'll be pushing it to my repository for the pull request as soon as I get git push straighted out with 2fa.
