### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by paulo242** [xdenser/node-firebird-libfbclient#66]
Ubuntu 16.10 64bit, NodeJS 4.2.6, npm 2.15.11, firebird client and server installed.

paulo@paulo-desktop:~/WebServiceRT1$ npm install
npm WARN package.json sqliteCreateDB@1.0.0 No description
npm WARN package.json sqliteCreateDB@1.0.0 No repository field.
npm WARN package.json sqliteCreateDB@1.0.0 No README data
npm WARN package.json sqliteCreateDB@1.0.0 No license field.
|
> firebird@0.0.13 install /home/paulo/WebServiceRT1/node_modules/firebird
> node-gyp rebuild

make: Entering directory '/home/paulo/WebServiceRT1/node_modules/firebird/build'
  CXX(target) Release/obj.target/binding/src/fb-bindings.o
In file included from ../src/././fb-bindings.h:11:0,
                 from ../src/./fb-bindings-connection.h:12,
                 from ../src/fb-bindings.cc:14:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^~~~~~~~~~~~~~
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^~~~~~~~~~~~~~
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^~~~~~~
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^~~~~~~~
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^~~~~~~~
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^~~~
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/././fb-bindings.h:11,
                 from ../src/./fb-bindings-connection.h:12,
                 from ../src/fb-bindings.cc:14:
/home/paulo/.node-gyp/4.2.6/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^~~
/home/paulo/.node-gyp/4.2.6/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/././fb-bindings.h:11:0,
                 from ../src/./fb-bindings-connection.h:12,
                 from ../src/fb-bindings.cc:14:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/././fb-bindings.h:11,
                 from ../src/./fb-bindings-connection.h:12,
                 from ../src/fb-bindings.cc:14:
/home/paulo/.node-gyp/4.2.6/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^~~
/home/paulo/.node-gyp/4.2.6/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/././fb-bindings.h:11:0,
                 from ../src/./fb-bindings-connection.h:12,
                 from ../src/fb-bindings.cc:14:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^~~~
binding.target.mk:104: recipe for target 'Release/obj.target/binding/src/fb-bindings.o' failed
make: *** [Release/obj.target/binding/src/fb-bindings.o] Error 1
make: Leaving directory '/home/paulo/WebServiceRT1/node_modules/firebird/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-27-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/paulo/WebServiceRT1/node_modules/firebird
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> sqlite3@3.1.8 install /home/paulo/WebServiceRT1/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/home/paulo/WebServiceRT1/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! firebird@0.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebird@0.0.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the firebird package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs firebird
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls firebird
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/paulo/WebServiceRT1/npm-debug.log

**Comment by mariuz** [comment]
please use latest release 0.0.14

https://www.npmjs.com/package/firebird

**Comment by paulo242** [comment]
Hi. Thanks for the reply. I used latest version and just tried 0.0.13. Same error.

**Comment by mariuz** [comment]
please send the error with  0.0.14

**Comment by paulo242** [comment]
> firebird@0.0.14 install /media/paulo/HD 1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird
> node-gyp rebuild

make: Entering directory '/media/paulo/HD 1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird/build'
  CXX(target) Release/obj.target/binding/src/fb-bindings.o
g++: error: 1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird/fb/include: Arquivo ou diretório não encontrado
binding.target.mk:104: recipe for target 'Release/obj.target/binding/src/fb-bindings.o' failed
make: *** [Release/obj.target/binding/src/fb-bindings.o] Error 1
make: Leaving directory '/media/paulo/HD 1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-27-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/paulo/HD 1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! firebird@0.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebird@0.0.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the firebird package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs firebird
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls firebird
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/paulo/HD 1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/npm-debug.log

**Comment by xdenser** [comment]
> 1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird/fb/include: Arquivo ou diretório não encontrado
file not found?

1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird/fb/include does not esist on your system by some reason

try to delete
1TB/GitRT1/Fontes/NodeJS/WebServiceRT1/node_modules/firebird
and reinstall
