### ISSUE TITLE
Unable to connect to firebird 3

### ISSUE THREAD

**Issue by mreis1** [xdenser/node-firebird-libfbclient#78]
I've a server running firebird on port 3050 (default). This server ip local ip address is 192.168.0.120.
The database alias is correctly configure to V12_M.

I downloaded and installed the sample node-libfbclient demo app.
And created my connection with the following settings:

Connection Name: "SERVER_LOCAL"
datatabase: "168.168.0.120/3050:V12_M"
user: "SYSDBA"
password: "MY_CUSTOM_PASSWORD"
role: ""

**[Attempt 1]** 
Having a default firebird.conf and the settings above when checking the connection I get 
"Error: While connecting - connection rejected by remote interface"

After googling I found that on windows it's possible to manage the service and enable the connection between the service and the desktop. I enabled it and restarted the service and I retried to connect but still got the same error.

Also it's not a problem of firewall since I disabled it on purpose.

**[Attempt 2]** 
1. Updated the firebird.conf 
WireCrypt = Disabled
AuthServer = Legacy_Auth, Srp, Win_Sspi
AuthClient = Legacy_Auth, Srp, Win_Sspi
2. Restarted the DBMS
3. Check connection returns:
Error: While connecting - Your user name and password are not defined. 
Ask your database administrator to set up a Firebird login.

**[Attempt 3]**
1. Removed the lines added on the previous attempt and added WireCrypt = Enabled to the bottom of the .conf file like I did on step 2.
2. Clicked "Check connection" and received "Error: While connecting - unknown ISC error 335545106"

**Note:** 
The database settings are correct. I tested a remote/local connection to both, a linux ubuntu and windows 7. 

Any tips? 
Thank you

**Comment by jacobalberty** [comment]
This is more an issue with firebird than node-firebird-libfbclient, because I use firebird 3.0.2 just fine. For attempt #2 did you initialize the legacy_auth db after applying those settings?

https://www.firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-compat-initsec.html Should get you started for initializing the db.

**Comment by mreis1** [comment]
After a second attempt I fixed the problem following your instructions @jacobalberty **security3.fdb.**. I'm still not sure what was going wrong but after all it works in both. Firebird 3 with WireCrypt Enabled and disabled, with and without Legacy Auth.
