### ISSUE TITLE
Password length sent by module is never longer than 8 characters.

### ISSUE THREAD

**Issue by asgeira13** [xdenser/node-firebird-libfbclient#79]
Recently started using this module for my node project to connect to my firebird 3.0.2 database. 
After integrating it into my project i started having problems connecting with my firebase users. Only one of my users could connect. Everyone else would get this error:

"While connecting - Your user name and password are not defined. Ask your database administrator to set up a Firebird login."

I had tried logging in with my firebird client with no problem so the passwords were correct. 

I started debugging with the sample project (which btw was extremely helpful) and eventually with the help of the online firebird manuals figured out that before version 3 the passwords could only be of length 8. Using the sample project I confirmed this and have now only created users with password length maximum 8.

So the issue is that the module only stores the first 8 characters of the password to send to the server but firebird servers of version 3 expect the whole password.

Hopefully this can help others who encounter the same issue and maybe a solution can be found.

**Comment by mariuz** [comment]
fixed by this pull request 

https://github.com/xdenser/node-firebird-libfbclient/pull/81

**Comment by mariuz** [comment]
This can be closed now :)
