### ISSUE TITLE
File not found (WSL)

### ISSUE THREAD

**Issue by strarsis** [xdenser/node-firebird-libfbclient#84]
````
Error: While connecting - I/O error during "CreateFile (open)" operation for file "./test.fdb"                                            Error while trying to open file
````

According to `strace`, `readlink` is called on the file path which returns `-1 EINVAL (Invalid argument)`.
I also tried to use a symlink to the actual file, but then it is tried again on the real existing file.

Apparently a loop is used with `readlink` in Firebird itself:
https://github.com/FirebirdSQL/firebird/blob/26192efca4f0e5245ad044fc608ade762f580d75/src/common/isc_file.cpp#L1211

**Comment by mariuz** [comment]
this is mostly a WSL bug , can be closed
