### ISSUE TITLE
is not a valid database

### ISSUE THREAD

**Issue by ShineWellSnake** [xdenser/node-firebird-libfbclient#89]
hello，
i created a new database and query data from it ,everything is ok.
but i try to open a *.ib file and  return this error
`F:\node-workspace\Hospital\edgeDemo.js:4
con.connectSync('d:\\xswhis.ib','sysdba','masterkey','');
    ^

Error: While connecting - file D:\XSWHIS.IB is not a valid database`

but i open it success by "FbMaestro.exe".

**Comment by mariuz** [comment]
This is not a Firebird database , it's an interbase db

**Comment by mariuz** [comment]
can be closed
